baseURL = 'https://daruyanagi.jp/'
languageCode = 'ja-jp'
title = 'daruyanagi'

hasCJKLanguage = true
enableGitInfo = true
paginate = 20
defaultContentLanguage = "ja"

# publishDir = "docs"
# publishDir = "../docs"
# relativeURLs = true

theme = 'hugo-coder'

[params]
  author = "YANAGI Hidetoshi"
  info = "daruyanagi"
  description = "YANAGI Hidetoshi, aka daruyanagi's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://pbs.twimg.com/profile_images/1486854996163391490/3uoc6IV7_400x400.jpg"
  #gravatar = "mail@daruyanagi.jp"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2018

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  [taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[markup.highlight]
  style = "monokai"

# Social links
[[params.social]]
  name = "Facebook"
  icon = "fa-brands fa-facebook fa-2x"
  weight = 3
  url = "https://facebook.com/YanagiHidetoshi/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/YanagiHidetoshi/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 5
  url = "https://github.com/daruyanagi/"
[[params.social]]
  name = "Skype"
  icon = "fa-brands fa-skype fa-2x"
  weight = 7
  url = "https://join.skype.com/invite/wgp9kEBqGczq"
[[params.social]]
  name = "Amazon"
  icon = "fa-brands fa-amazon fa-2x"
  weight = 10
  url = "https://amzn.asia/4Geihep"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"